{
  "GGCAL.Title": "GG Calendar",
  "GGCAL.OpenCalendar": "Abrir GG Calendar",
  "GGCAL.Today": "Hoy",
  "GGCAL.RollWeather": "Clima",
  "GGCAL.Controls.Hint": "Click izquierdo avanza el tiempo, click derecho retrocede.",
  "GGCAL.Preset.gregorian": "Gregoriano (Tierra)",
  "GGCAL.Preset.harptos": "Calendario de Harptos (Reinos Olvidados)",
  "GGCAL.Preset.greyhawk": "Greyhawk (Año Común)",
  "GGCAL.Preset.custom": "Personalizado (JSON abajo)",
  "GGCAL.Settings.Preset.Name": "Calendario activo",
  "GGCAL.Settings.Preset.Hint": "Elegí un calendario integrado o seleccioná Personalizado para usar tu propia definición JSON.",
  "GGCAL.Settings.CustomConfig.Name": "Calendario personalizado (JSON)",
  "GGCAL.Settings.CustomConfig.Hint": "Se usa solo cuando el calendario activo es Personalizado. Definí meses (con festivales intercalares y leapDays opcionales), días de la semana, regla de años bisiestos, época y estaciones.",
  "GGCAL.Settings.Climate.Name": "Clima del mundo",
  "GGCAL.Settings.Climate.Hint": "Alimenta el generador de clima dinámico junto con la estación actual.",
  "GGCAL.Settings.AutoWeather.Name": "Clima diario automático",
  "GGCAL.Settings.AutoWeather.Hint": "Genera clima nuevo en el chat cada vez que cambia el día en el juego.",
  "GGCAL.Settings.TempUnit.Name": "Unidad de temperatura",
  "GGCAL.Settings.RestAdvance.Name": "Avanzar tiempo con descansos de D&D 5e",
  "GGCAL.Settings.RestAdvance.Hint": "El descanso corto avanza 1 hora y el largo 8 horas al completarse.",
  "GGCAL.Settings.CombatAdvance.Name": "Avanzar tiempo por ronda de combate",
  "GGCAL.Settings.CombatAdvance.Hint": "Solo para sistemas que no avanzan el tiempo por ronda automáticamente (D&D 5e ya lo hace — dejalo apagado ahí).",
  "GGCAL.Settings.SecondsPerRound.Name": "Segundos por ronda de combate",
  "GGCAL.Climate.temperate": "Templado",
  "GGCAL.Climate.cold": "Frío / Subártico",
  "GGCAL.Climate.arid": "Árido / Desierto",
  "GGCAL.Climate.tropical": "Tropical",
  "GGCAL.Weather.clear": "Cielo despejado",
  "GGCAL.Weather.cloudy": "Nublado",
  "GGCAL.Weather.rain": "Lluvia",
  "GGCAL.Weather.storm": "Tormenta eléctrica",
  "GGCAL.Weather.fog": "Niebla",
  "GGCAL.Weather.snow": "Nevada",
  "GGCAL.Weather.blizzard": "Ventisca",
  "GGCAL.Weather.scorching": "Calor abrasador",
  "GGCAL.Weather.sandstorm": "Tormenta de arena",
  "GGCAL.Weather.humid": "Bruma húmeda",
  "GGCAL.Notes.Title": "Notas",
  "GGCAL.Notes.Empty": "No hay notas en esta fecha.",
  "GGCAL.Notes.Untitled": "Nota sin título",
  "GGCAL.Notes.NewTitle": "Título",
  "GGCAL.Notes.TitlePh": "Festival de la Luna, llega la caravana...",
  "GGCAL.Notes.NewText": "Texto",
  "GGCAL.Notes.GMOnly": "Solo GM",
  "GGCAL.Notes.Add": "Agregar nota",
  "GGCAL.SetDate.Title": "Establecer fecha y hora del mundo",
  "GGCAL.SetDate.Button": "Fijar fecha",
  "GGCAL.SetDate.Year": "Año",
  "GGCAL.SetDate.Month": "Mes",
  "GGCAL.SetDate.Day": "Día",
  "GGCAL.SetDate.Time": "Hora (hh : mm)",
  "GGCAL.SetDate.Confirm": "Saltar a la fecha",
  "GGCAL.Time.RestAdvanced": "GG Calendar: avanzó {hours}h tras el descanso de {name}.",
  "GGCAL.Errors.GMOnly": "Solo el GM puede cambiar el tiempo del mundo.",
  "GGCAL.Errors.BadCustomJSON": "GG Calendar: tu JSON de calendario personalizado no es válido. Se usará el Gregoriano.",
  "GGCAL.Moon.new": "Luna nueva",
  "GGCAL.Moon.waxingCrescent": "Creciente iluminante",
  "GGCAL.Moon.firstQuarter": "Cuarto creciente",
  "GGCAL.Moon.waxingGibbous": "Gibosa creciente",
  "GGCAL.Moon.full": "Luna llena",
  "GGCAL.Moon.waningGibbous": "Gibosa menguante",
  "GGCAL.Moon.lastQuarter": "Cuarto menguante",
  "GGCAL.Moon.waningCrescent": "Creciente menguante",
  "GGCAL.Notes.OpenJournal": "Abrir en diario",
  "GGCAL.Journal.Name": "GG Calendar — Crónica de campaña",
  "GGCAL.Settings.WorldCalendar.Name": "Registrar como calendario del mundo",
  "GGCAL.Settings.WorldCalendar.Hint": "En Foundry v13+, hace que GG Calendar sea el calendario canónico del mundo para que otros módulos lean su fecha y formato. Requiere recargar. Sin efecto en v12.",
  "GGCAL.Settings.SCBridge.Name": "Compatibilidad con Simple Calendar",
  "GGCAL.Settings.SCBridge.Hint": "Expone una API compatible con Simple Calendar para que los módulos que dependen de él sigan funcionando. Solo se activa si Simple Calendar no está instalado. Requiere recargar.",
  "GGCAL.Chronicle.Button": "Crónica",
  "GGCAL.Chronicle.Title": "Crónica de campaña",
  "GGCAL.Chronicle.Compile": "Compilar al diario",
  "GGCAL.Chronicle.Clear": "Vaciar registro",
  "GGCAL.Chronicle.ClearConfirm": "¿Eliminar todos los eventos registrados? Esto no se puede deshacer.",
  "GGCAL.Chronicle.Empty": "Aún no hay eventos registrados. Los combates, descansos y cambios de escena aparecerán aquí.",
  "GGCAL.Chronicle.Marked": "Hito narrativo registrado.",
  "GGCAL.Chronicle.CombatStart": "Comenzó un combate ({n} combatientes).",
  "GGCAL.Chronicle.CombatEnd": "El combate terminó tras {rounds} rondas.",
  "GGCAL.Chronicle.ShortRest": "{name} hizo un descanso corto.",
  "GGCAL.Chronicle.LongRest": "{name} hizo un descanso largo.",
  "GGCAL.Chronicle.Scene": "Llegada a {name}.",
  "GGCAL.Chronicle.SessionTitle": "Sesión — {date}",
  "GGCAL.Chronicle.SessionRange": "Sesión — {from} a {to}",
  "GGCAL.Settings.Chronicle.Name": "Crónica automática de eventos",
  "GGCAL.Settings.Chronicle.Hint": "Registra automáticamente combates, descansos y cambios de escena con marcas de tiempo del mundo, listos para compilar en un diario de sesión.",
  "GGCAL.Region.climate.label": "Clima",
  "GGCAL.Region.rollWeatherOnEnter.label": "Generar clima al entrar",
  "GGCAL.Region.particleEffect.label": "Efecto de partículas de clima",
  "GGCAL.Region.statusEffect.label": "ID de efecto de estado (opcional)",
  "GGCAL.Region.announce.label": "Anunciar clima en el chat",
  "GGCAL.Region.FIELDS.climate.label": "Clima",
  "GGCAL.RegionType.climateZone": "Zona climática GG"
}